### ISSUE TITLE
Should send message to client on (re-)connect or handle re-subscribes also

### ISSUE THREAD

**Issue by Hades32** [emqtt/emqttc#10]
When the MQTT connection is broken and re-established, the subscriptions are gone. (Just like expected) This means that the client as to re-subscribe to his topics. But as there is no (info) message for this event, there is no option to do so.

My proposal is to have a `handle_info(connected, State = #state{mqttc = C, seq = I})` function which is *always* called after connack, no matter if it is the first connect or a reconnect. Thus this method can be a central point for managing subscriptions.

Alternatively the client could remember the subscriptions and restore them after a reconnect. But I don't think this would be a good idea: Many clients use last-will messages which trigger some stuff and then use on-connected callbacks to indicate to the application that they have regained connection. Therefore a manual connected handling would be preferable IMHO.

**Comment by Hades32** [comment]
I implemented some crude hack, to have some kind of connection listener: https://github.com/Hades32/emqttc/commit/e7cc33a181ec0e188387b74cff5ccf08d0f8a769 (It's my first lines of Erlang, so don't take it to seriuosly ;) ) It's just to illustrate what I'm trying to have.

**Comment by erylee** [comment]
hi Martin, you did right:) The emqttc should emit 'connected', 'disconnected' event to the user process. 

I replace the connection_listener with parent process. Please pull the latest commit to check if it works for your requirements.

**Comment by erylee** [comment]
Example code: 'emqttc/examples/gen_server/src/gen_server_example.erl'

**Comment by erylee** [comment]
Added a 'auto_resub' flag.   

```
{ok, C} = emqttc:start_link([{client_id, <<"testClient">>}, auto_resub, {reconnect, 3}]).
```

emqttc client will resubscribe topics automatically when reconnected if this flag is set.

**Comment by Hades32** [comment]
Great solution! Thanks!
