### ISSUE TITLE
latest build fail in erlang:timestamp/0 for R17

### ISSUE THREAD

**Issue by mingchuno** [emqtt/emqttc#36]
https://travis-ci.org/emqtt/emqttc/jobs/132012920

`src/emqttc_protocol.erl:125: Warning: emqttc_protocol:random_id/0 calls undefined function erlang:timestamp/0 (Xref)`

**Comment by emqplus** [comment]
;) Warning when building with Erlang R17?

**Comment by mingchuno** [comment]
@emqplus noop, can't even build on R17

**Comment by emqplus** [comment]
@mingchuno, fixed.
