### ISSUE TITLE
Does not work with Erlang 21

### ISSUE THREAD

**Issue by gotthardp** [emqtt/emqttc#62]
The gen_logger crashes, probably due to https://github.com/emqtt/gen_logger/issues/5

Since mqttd uses lager, wouldn't it be better to get rid of the gen_logger and use lager instead?

**Comment by terry-xiaoyu** [comment]
Yes, it is caused by the `parameterized module`. We'll update this project based on OTP 21 and release it as 'emqx-client' in EMQ R3.0.

**Comment by emqplus** [comment]
@gotthardp This project will be upgraded to emqx-client, and released with EMQ X 3.0. The first tag will be ready this weekend.

**Comment by gotthardp** [comment]
@emqplus Thanks a lot! That's perfect.

**Comment by manifest** [comment]
@emqplus, is the release delayed?

**Comment by arpunk** [comment]
I was not aware that lager was the consensus. I just submited #63 which removes gen_logger and relies on the Erlang modules for logging. I can switch to lager if there is interest.

**Comment by zhaoweiguo** [comment]
@emqplus 
So when EMQ X 3.0 will be released?

**Comment by zhaoweiguo** [comment]
@Gilbert-Wong 
Therefore, Since MQTT v5.0 is not backward compatible, we don't need to wait for the release of EMQ X 3.0

**Comment by Gilbert-Wong** [comment]
Yes

**Comment by gotthardp** [comment]
So, EMQ X 3.0 will support MQTT 5 only and this repository will continue to be used for MQTT 3.1? Do you plan any MQTT 3 related updates, or shall we propose updates for OTP 21? Will you at least continue to maintain this? (There are unaccepted pull requests for some time already.)

**Comment by Gilbert-Wong** [comment]
Yes, this repository will be replaced with `emqx/emqx_client.erl` and both the implementation of mqtt v3.1 and mqtt v5.0 would be maintained.

**Comment by gotthardp** [comment]
Replaced (emqx will support mqtt 3) or both this repository and emqx will continue exist in parallel?

**Comment by tkeksa** [comment]
Do you plat to provide smaller client library or whole `emqx`  has to be used?

**Comment by Gilbert-Wong** [comment]
We have schedule to provide smaller client library later.

**Comment by hommeabeil** [comment]
I was looking in the source code and the history and I find [this commit](https://github.com/emqtt/emqttc/commit/9ccff9bd2d0b0e4095b6ec5af69384767cbbee8c). Does this fix this issue ?

**Comment by Gilbert-Wong** [comment]
Nope, but it should work with erlang 21 now. You can try with it.
