### ISSUE TITLE
Would it be possible to apply a tag to the latest version?

### ISSUE THREAD

**Issue by Boilerfan86** [emqtt/emqttc#70]
Hello,

We would like to use the latest version of this package, but our software clearing team would like for us to pull the code based on a tag and not the latest version.  Would it be possible for the maintainer to tag the latest version on the master branch so we could pull by that tag?

Thank you!
David Wolf

**Comment by Gilbert-Wong** [comment]
Of course, @Boilerfan86, soon tag the latest version.

**Comment by Gilbert-Wong** [comment]
This library has been tagged to 0.8.0 now. :)

**Comment by Boilerfan86** [comment]
@Gilbert-Wong Thank you!
