### ISSUE TITLE
Crash after "Merge branch 'hiroeorz-master'" 7c6de640c6a3afadb6f9bb35d515411384a159ae

### ISSUE THREAD

**Issue by desoulter** [emqtt/emqttc#8]
Hi,

I can't start emqtcc after 7c6de640c6a commit.

(messenger@127.0.0.1)2> {ok, Pid} = emqttc:start_link([{host, "test.mosquitto.org"}]).
** exception exit: {badmatch,false}
     in function  emqttc:init/1 (src/emqttc.erl, line 269)
     in call from gen_fsm:init_it/6 (gen_fsm.erl, line 363)
     in call from proc_lib:init_p_do_apply/3 (proc_lib.erl, line 239)
(messenger@127.0.0.1)3> 11:48:42.453 [error] CRASH REPORT Process <0.322.0> with 1 neighbours exited with reason: no match of right hand value false in emqttc:init/1 line 269 in gen_fsm:init_it/6 line 381

**Comment by erylee** [comment]
desoulter , pls use emqttc:start_link([{host, "localhost"}, {client_id, "clientId"}]). I will release a fix today

**Comment by erylee** [comment]
generate a random clientid if not provided.

init([Name, Args]) ->
-    true = proplists:is_defined(client_id, Args),
-    ClientId = proplists:get_value(client_id, Args),
+    %true = proplists:is_defined(client_id, Args),
+    {_, Secs, MicroSecs} = erlang:now(),
+    RandomId = list_to_binary(["emqttc-", integer_to_list(Secs), "-", integer_to_list(MicroSecs)]),
+    ClientId = proplists:get_value(client_id, Args, RandomId),
