### ISSUE TITLE
If emqttc is not started as "emqttc" the event handling fails

### ISSUE THREAD

**Issue by everydaysasaturday** [emqtt/emqttc#9]
in emqttc_event line 93 - 97.

handle_event({publish, Topic, Payload, 1, MsgId}, State) ->
    io:format("publish: topic(id:~p):~p~n", [MsgId, Topic]),
    io:format("publish: payload:~p~n", [Payload]),
    emqttc:puback(emqttc, MsgId),
    {ok, State};

**Comment by erylee** [comment]
@everydaysasaturday The API of 0.1 release is not right. A caller don't need to puback.

0.2.0 release rewrite the whole project and redesign the API, please check the README.md.
